[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "biogaip"
version = "1.3.1"
dependencies = [
    "streamlit==1.59.0",
    "streamlit-cookies-manager==0.2.0",
    "autogen-agentchat==0.7.5",
    "autogen-core",
    "autogen-ext",
    "requests",
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "openai",
    "anthropic",
    "ollama",
    "sqlalchemy",
    "psycopg2-binary",
    "loguru",
    "pyyaml",
    "onnx==1.18.0",
    "paramiko",
    "aiofiles",
    "chromadb==1.5.9",
    "playwright",
    "pymed",
    "azure-core",
    "pypdf",
    "azure-keyvault-secrets",
    "chainlit==2.6.2",
    "tiktoken",
    "psutil==7.0.0"
]
requires-python = ">=3.10"
readme = "README.md"

[project.scripts]
biogaip = "bioGen.cli:main"
biogen = "bioGen.cli:main"
session_explorer = 'bioGen.web_v2.session_explorer:run_gui'

[tool.setuptools.package-data]
biogaip = ["*", "*/*", "*/*/*", "*/*/*/*", "*/*/*/*/*", "*/*/*/*/*/*", "pubmed/**/*", "config/**"]
bioGen = ["config/*.yaml", "config/**/*.yaml"]
#biogaip = []
#biogaip = ["config/**"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true